select * from INDICES
select * from indexadores
DELETE INDEXADORES
drop table indices

--Insert da Tabela convertida (http://dbfconv.com/) para a tabela do Sistema Gitano
--
INSERT INTO indexadores
(NOME,PERIODICIDADE,INICIO,FIM,DIVULGACAO,TIPO,DMAIS,ATIVO,DESCRICAO,ORGAO,OBSERVA_1,OBSERVA_2)
select NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D,1,'','','','' from INDICES order by NOME
--

-- Script Sql de inclusão dos registros
--
CREATE TABLE INDICES (
   NOME CHAR(10), 
   PERIODO CHAR(10), 
   INICIO INTEGER, 
   FIM INTEGER, 
   DIVULGACAO INTEGER, 
   TIPO CHAR(10), 
   D INTEGER);


INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('IPC_R','MENSAL','','','','TAXA','')

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('TR_D','DIARIO','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('POUPANCA','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('IGP_M','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('CUB','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('CUB_E','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('NENHUM','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('IGP_E','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('IGP_ME','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('CO_LA','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('CO_LU','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('CO_LUG','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('INCC','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('CO_VA','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('INPC','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('CO_CAR','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('UVAIAS','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('A_UVAIAS','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('PARAC','MENSAL','','','','TAXA','');

INSERT INTO INDICES
  (NOME,PERIODO,INICIO,FIM,DIVULGACAO,TIPO,D)
VALUES 
  ('ADRIATICO','MENSAL','','','','TAXA','');


COMMIT;
